// Generated by CoffeeScript 1.6.3
define(['underscore', 'backbone', 'models/post'], function(_, Backbone, Post) {
  'use strict';
  return Backbone.Collection.extend({
    model: Post,
    url: '/posts',
    index: function() {
      this.deactive();
      return this.trigger('render');
    },
    show: function(id) {
      this.active(id);
      return this.trigger('render');
    },
    active: function(activeId) {
      this.activeId = activeId;
    },
    deactive: function(activeId) {
      this.activeId = activeId != null ? activeId : void 0;
    },
    currentPost: function() {
      return this.get(this.activeId);
    },
    currentIndex: function() {
      return this.indexOf(this.currentPost());
    },
    offsetPost: function(offset) {
      var index;
      index = this.currentIndex() + offset;
      if (index > -1 && index < this.size()) {
        return this.at(index);
      }
    },
    getTags: function() {
      var _this = this;
      if (!this.tagCollection) {
        this.tagCollection = [];
        this.each(function(post) {
          if (post.get('tags')) {
            return _this.tagCollection = _.union(_this.tagCollection, post.getTags());
          }
        });
      }
      return this.tagCollection;
    }
  });
});
