// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'backbone', 'collections/posts', 'routers/router', 'views/index', 'views/main', 'views/loading', 'text!templates/tag-link.html', 'text!templates/post-title.html'], function($, _, Backbone, posts, router, Index, Main, Loading, tagLink, postTitle) {
  'use strict';
  return Backbone.View.extend({
    el: '#main_content_wrap',
    tagLinkTemplate: _.template(tagLink),
    postTitleTemplate: _.template(postTitle),
    initialize: function() {
      var _this = this;
      this.$title = $('#post_title');
      this.$tags = $('#header_wrap #tags');
      this.items = {
        main: new Main,
        index: new Index({
          tagLinkTemplate: this.tagLinkTemplate
        }),
        loading: new Loading
      };
      _.each(this.items, function(item, mode) {
        item.$el.hide();
        return _this.$el.append(item.el);
      });
      this.listenTo(posts, 'render', this.render);
      return posts.load();
    },
    render: function() {
      var newMode, view,
        _this = this;
      newMode = !posts.ready ? 'loading' : posts.activeId ? 'main' : 'index';
      view = this.items[newMode].render();
      if (newMode !== this.currentMode) {
        this.currentMode = newMode;
        _.each(this.items, function(item, mode) {
          return item.$el.hide();
        });
        view.$el.show();
        switch (this.currentMode) {
          case 'main':
            this.$title.show();
            break;
          case 'index':
            this.$title.hide();
        }
      }
      this.headRender();
      return this;
    },
    headRender: function() {
      var post, tags,
        _this = this;
      this.$tags.empty();
      post = posts.currentPost();
      if (post) {
        this.$title.html(this.postTitleTemplate({
          title: post.get('title'),
          time: post.getTime().toLocaleString()
        }));
        tags = post.getTags();
      } else {
        tags = posts.getTags();
      }
      return _.each(tags, function(tag) {
        return _this.$tags.append(_this.tagLinkTemplate({
          name: tag,
          link: '#/tags/' + tag
        }));
      });
    }
  });
});
