// Generated by CoffeeScript 1.6.3
'use strict';
require.config({
  paths: {
    jquery: 'lib/jquery-2.0.3.min',
    underscore: 'lib/underscore-min',
    backbone: 'lib/backbone.min',
    bootstrap: 'lib/bootstrap.min'
  },
  shim: {
    backbone: ['jquery', 'underscore'],
    bootstrap: ['jquery']
  }
});

require(['backbone', 'views/app', 'routers/router'], function(Backbone, AppView, Router) {
  new Router();
  Backbone.history.start();
  return new AppView();
});
