// Generated by CoffeeScript 1.6.3
define(['backbone', 'collections/posts'], function(Backbone, posts) {
  return new (Backbone.Router.extend({
    routes: {
      'posts/*id': 'postShow',
      'tags/*tag': 'filterTag',
      '*interceptor': 'interceptor'
    },
    postShow: function(param) {
      return posts.show(param);
    },
    filterTag: function() {
      return posts.index();
    },
    interceptor: function() {
      return posts.index();
    }
  }));
});
